default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sandri4
  password: 3699

development:
  <<: *default
  database: lesson4_development
test:
  <<: *default
  database: lesson4_test
production:
  <<: *default
  database: lesson4_production
